/**
 * Icon — maps a stable string name to a Lucide icon component. Using names (not
 * imported components) keeps the department catalog (src/lib/departments.ts) plain
 * data while rendering crisp SVG icons instead of emojis. Works in both server and
 * client components (Lucide icons are pure SVG, no hooks).
 */
import {
  Home,
  Users,
  Building2,
  Tag,
  ShoppingCart,
  Wallet,
  Megaphone,
  Package,
  FileText,
  HelpCircle,
  UserRound,
  CheckCircle2,
  Table,
  Rocket,
  Target,
  ListTodo,
  Settings,
  UserCog,
  Truck,
  Factory,
  Crown,
  Download,
  Printer,
  MessageSquare,
  Gauge,
  Scale,
  Car,
  Shield,
  ClipboardList,
  Fuel,
  Inbox,
  Send,
  Plug,
  PieChart,
  Search,
  X,
  Loader2,
  AlertCircle,
  AlertTriangle,
  Plus,
  ChevronRight,
  ChevronDown,
  LogOut,
  LayoutDashboard,
  Layout,
  Pin,
  PinOff,
  Minimize2,
  Maximize2,
  Minus,
  PanelRight,
  MoveDiagonal,
  Sparkles,
  // Spatial Executive OS — command rail, instruments and evidence surfaces.
  Activity,
  Radar,
  Compass,
  CalendarDays,
  CalendarClock,
  Boxes,
  FolderOpen,
  ShieldAlert,
  Bot,
  HeartPulse,
  TrendingUp,
  TrendingDown,
  Clock,
  ArrowRight,
  ArrowUpRight,
  Command as CommandIcon,
  Bell,
  MapPin,
  Circle,
  Info,
  Eye,
  Lightbulb,
  Banknote,
  Landmark,
  Receipt,
  GitBranch,
  Network,
  Layers,
  Filter,
  ChevronLeft,
  ChevronsLeft,
  ChevronsRight,
  PanelLeft,
  Mic,
  Paperclip,
  CornerDownLeft,
  Briefcase,
  FileCheck,
  ScrollText,
  Gavel,
  Wrench,
  Warehouse,
  Timer,
  Zap,
  Database,
  Server,
  BookOpen,
  Flag,
  ExternalLink,
  MoreHorizontal,
  Grid3x3,
  Rows3,
  Share2,
  Lock,
  Unlock,
  RefreshCw,
  WifiOff,
  Image as ImageIcon,
  type LucideIcon,
} from "lucide-react";

const MAP: Record<string, LucideIcon> = {
  home: Home,
  users: Users,
  "building-2": Building2,
  tag: Tag,
  "shopping-cart": ShoppingCart,
  wallet: Wallet,
  megaphone: Megaphone,
  package: Package,
  "file-text": FileText,
  "help-circle": HelpCircle,
  "user-round": UserRound,
  "check-circle": CheckCircle2,
  table: Table,
  rocket: Rocket,
  target: Target,
  "list-todo": ListTodo,
  settings: Settings,
  "user-cog": UserCog,
  truck: Truck,
  factory: Factory,
  crown: Crown,
  download: Download,
  printer: Printer,
  "message-square": MessageSquare,
  gauge: Gauge,
  scale: Scale,
  car: Car,
  shield: Shield,
  clipboard: ClipboardList,
  fuel: Fuel,
  inbox: Inbox,
  send: Send,
  plug: Plug,
  "pie-chart": PieChart,
  search: Search,
  x: X,
  "loader-2": Loader2,
  "alert-circle": AlertCircle,
  "alert-triangle": AlertTriangle,
  "check-circle-2": CheckCircle2,
  plus: Plus,
  "chevron-right": ChevronRight,
  "chevron-down": ChevronDown,
  "log-out": LogOut,
  layout: Layout,
  pin: Pin,
  "pin-off": PinOff,
  "minimize-2": Minimize2,
  "maximize-2": Maximize2,
  minus: Minus,
  "panel-right": PanelRight,
  "move-diagonal": MoveDiagonal,
  sparkles: Sparkles,

  // ── Spatial Executive OS ────────────────────────────────────────────────
  activity: Activity,
  radar: Radar,
  compass: Compass,
  "calendar-days": CalendarDays,
  "calendar-clock": CalendarClock,
  boxes: Boxes,
  "folder-open": FolderOpen,
  "shield-alert": ShieldAlert,
  bot: Bot,
  "heart-pulse": HeartPulse,
  "trending-up": TrendingUp,
  "trending-down": TrendingDown,
  clock: Clock,
  "arrow-right": ArrowRight,
  "arrow-up-right": ArrowUpRight,
  command: CommandIcon,
  bell: Bell,
  "map-pin": MapPin,
  circle: Circle,
  info: Info,
  eye: Eye,
  lightbulb: Lightbulb,
  banknote: Banknote,
  landmark: Landmark,
  receipt: Receipt,
  "git-branch": GitBranch,
  network: Network,
  layers: Layers,
  filter: Filter,
  "chevron-left": ChevronLeft,
  "chevrons-left": ChevronsLeft,
  "chevrons-right": ChevronsRight,
  "panel-left": PanelLeft,
  mic: Mic,
  paperclip: Paperclip,
  "corner-down-left": CornerDownLeft,
  briefcase: Briefcase,
  "file-check": FileCheck,
  "scroll-text": ScrollText,
  gavel: Gavel,
  wrench: Wrench,
  warehouse: Warehouse,
  timer: Timer,
  zap: Zap,
  database: Database,
  server: Server,
  "book-open": BookOpen,
  flag: Flag,
  "external-link": ExternalLink,
  "more-horizontal": MoreHorizontal,
  grid: Grid3x3,
  rows: Rows3,
  "share-2": Share2,
  lock: Lock,
  unlock: Unlock,
  "refresh-cw": RefreshCw,
  "wifi-off": WifiOff,
  image: ImageIcon,
};

export function Icon({
  name,
  size = 18,
  className,
  strokeWidth = 2,
}: {
  name: string;
  size?: number;
  className?: string;
  strokeWidth?: number;
}) {
  const C = MAP[name] ?? LayoutDashboard;
  return <C size={size} strokeWidth={strokeWidth} className={className} aria-hidden />;
}
